<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container615M3BF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container615M3BF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container615M3BF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container615M3BF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container615M3BF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '615M3BF',
    'container.build_id' => '21b2aef9',
    'container.build_time' => 1612816635,
], __DIR__.\DIRECTORY_SEPARATOR.'Container615M3BF');
