<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    'category_index' => [[], ['_controller' => 'App\\Controller\\CategoryController::index'], [], [['text', '/category/']], [], []],
    'category_new' => [[], ['_controller' => 'App\\Controller\\CategoryController::new'], [], [['text', '/category/new']], [], []],
    'category_show' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/category']], [], []],
    'category_edit' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/category']], [], []],
    'category_delete' => [['id'], ['_controller' => 'App\\Controller\\CategoryController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/category']], [], []],
    'menu' => [[], ['_controller' => 'App\\Controller\\MenuController::index'], [], [['text', '/']], [], []],
    'plat_index' => [[], ['_controller' => 'App\\Controller\\PlatController::index'], [], [['text', '/plat/']], [], []],
    'plat_new' => [[], ['_controller' => 'App\\Controller\\PlatController::new'], [], [['text', '/plat/new']], [], []],
    'plat_show' => [['id'], ['_controller' => 'App\\Controller\\PlatController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/plat']], [], []],
    'plat_edit' => [['id'], ['_controller' => 'App\\Controller\\PlatController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/plat']], [], []],
    'plat_delete' => [['id'], ['_controller' => 'App\\Controller\\PlatController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/plat']], [], []],
];
